// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjgR-6rOD2cRdxnCErAL-huJfu-c3ZGDo',
    appId: '1:968602749015:web:21dcdc2d7f585e1c5bfb12',
    messagingSenderId: '968602749015',
    projectId: 'qestak-11e3a',
    authDomain: 'qestak-11e3a.firebaseapp.com',
    storageBucket: 'qestak-11e3a.firebasestorage.app',
    measurementId: 'G-772J3XPNBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQPKX_MRIImqalZpWjlkGyMzO2WDyVCg',
    appId: '1:968602749015:android:3789331965f11bb15bfb12',
    messagingSenderId: '968602749015',
    projectId: 'qestak-11e3a',
    storageBucket: 'qestak-11e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDygb58NYJnqAvMIHALxuwu0lU7hgkmyVU',
    appId: '1:968602749015:ios:52627b9c6b3deb175bfb12',
    messagingSenderId: '968602749015',
    projectId: 'qestak-11e3a',
    storageBucket: 'qestak-11e3a.firebasestorage.app',
    iosBundleId: 'com.qestak.qestak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDygb58NYJnqAvMIHALxuwu0lU7hgkmyVU',
    appId: '1:968602749015:ios:52627b9c6b3deb175bfb12',
    messagingSenderId: '968602749015',
    projectId: 'qestak-11e3a',
    storageBucket: 'qestak-11e3a.firebasestorage.app',
    iosBundleId: 'com.qestak.qestak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjgR-6rOD2cRdxnCErAL-huJfu-c3ZGDo',
    appId: '1:968602749015:web:a10bd582d8ebbf2e5bfb12',
    messagingSenderId: '968602749015',
    projectId: 'qestak-11e3a',
    authDomain: 'qestak-11e3a.firebaseapp.com',
    storageBucket: 'qestak-11e3a.firebasestorage.app',
    measurementId: 'G-GX630VRDZY',
  );
}
